env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
